services:
  local-zookeeper:
    container_name: local-zookeeper
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  local-kafka:
    container_name: local-kafka
    image: wurstmeister/kafka
    depends_on:
      - local-zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 127.0.0.1
      KAFKA_ZOOKEEPER_CONNECT: local-zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
