services:
  local-redis:
    container_name: local-redis
    image: redis:7
    ports:
      - "6379:6379"
    networks:
      - redis
  local-zookeeper:
    container_name: local-zookeeper
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
    networks:
      - kafka
  local-kafka:
    container_name: local-kafka
    image: wurstmeister/kafka
    depends_on:
      - local-zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 127.0.0.1
      KAFKA_ZOOKEEPER_CONNECT: local-zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - kafka
  local-prometheus:
    container_name: local-prometheus
    image: prom/prometheus:latest
    volumes:
      - ./monitoring/prometheus/config:/etc/prometheus
      - ./monitoring/prometheus/volume:/prometheus
    ports:
      - "9090:9090"
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    networks:
      - monitoring
    restart: always
  local-grafana:
    container_name: local-grafana
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    volumes:
      - ./monitoring/grafana/volume:/var/lib/grafana
    networks:
      - monitoring
    restart: always
  local-node-exporter:
    image: prom/node-exporter
    ports:
      - "9100:9100"
    networks:
      - monitoring
  local-redis-exporter:
    image: oliver006/redis_exporter
    ports:
      - "9121:9121"
    environment:
      REDIS_ADDR: "local-redis:6379"
      REDIS_USER: null
    networks:
      - monitoring
      - redis
networks:
  monitoring:
    driver: bridge
  kafka:
    driver: bridge
  redis:
    driver: bridge
