management:
  metrics:
    tags:
      application: ${spring.application.name}
  endpoints:
    web:
      exposure:
        include: prometheus
server:
  tomcat:
    mbeanregistry:
      enabled: true
spring:
  application.name: foodie-server
  jpa:
    open-in-view: false
    properties:
      hibernate:
        default_batch_fetch_size: 50
api:
  endpoint:
    base-url: /api/v1
schedules:
  cron:
    user:
      delete: 0 0 3 * * *
    post:
      delete: 0 30 3 * * *
images:
  dir:
    user-profile: ${USER_PROFILE_IMAGE_DIR}
slack:
  token: ${SLACK_TOKEN}
jwt:
  secret: ${JWT_SECRET}
  expiration-time: 3600000 # 1000 * 60 * 60, 60분
