logging:
  level:
    org.hibernate.orm.jdbc.bind: TRACE

spring:
  application.name: foodieserver
  jpa:
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 50

api:
  endpoint:
    base-url: /api/v1

schedules:
  cron:
    user:
      delete: 0 0 3 * * *
---
spring:
  config.activate.on-profile: local
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${LOCAL_DB_URL}
    username: ${LOCAL_DB_USERNAME}
    password: ${LOCAL_DB_PASSWORD}
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
  sql.init.mode: always

