global:
  scrape_interval: 30s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "foodie-server"
    metrics_path: '/manage/prometheus'
    static_configs:
      - targets: [ 'app:8081' ]
  - job_name: 'node-exporter'
    static_configs:
      - targets: [ 'node-exporter:9100' ]
  - job_name: 'redis-exporter'
    static_configs:
      - targets: [ 'redis-exporter:9121' ]
